services:
  - type: web
    name: agricare
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
