name: agri_monitor
description: Agriculture Monitoring Platform - Smart farming meets AI-powered insights

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & State Management
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # HTTP & API
  dio: ^5.3.2
  http: ^1.1.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Database
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image & Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  photo_view: ^0.14.0
  
  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  
  # Charts & Visualization
  fl_chart: ^0.64.0
  
  # Network & Connectivity
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  
  # Notifications
  # flutter_local_notifications: ^16.1.0  # Temporarily disabled due to API compatibility issue
  
  # Utils & Helpers
  uuid: ^4.1.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  
  # Biometric & Security
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  cloud_firestore: ^4.13.6
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  
  # File Handling
  # file_picker: ^6.1.1  # Temporarily disabled due to v1 embedding issue
  path: ^1.8.3
  
  # UI Components
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  
  # Date & Time
  jiffy: ^6.2.1
  
  # Platform Integration
  share_plus: ^7.2.1
  
  # Text-to-Speech & Localization
  flutter_tts: ^3.8.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^3.0.1
  
  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
